<?php
$data = array (
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => 'Lace',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '6',
    'name' => 'Lace',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => 'Wigs',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => 'Wigs',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '360 wigs',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '360 wigs',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => 'Bob wigs',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 2,
    'level' => 1,
    'id' => '11',
    'name' => 'Bob wigs',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => 'Full lace wig',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '8',
    'name' => 'Full lace wig',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => 'color wigs',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '12',
    'name' => 'color wigs',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '13x4 frontal wigs',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '13x4 frontal wigs',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => 'closure wigs',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => 'closure wigs',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '13x6 frontal wigs',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '10',
    'name' => '13x6 frontal wigs',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => 'Bundles',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 0,
    'id' => '5',
    'name' => 'Bundles',
  ),
);
?>